#!/bin/bash

N=0
while read commit
do
  N=$(expr $N + 1)
  H=$(echo $commit | cut -d'#' -f 1)
  S=$(echo $commit | cut -d'#' -f 2)
  WHO=$(echo $commit | cut -d'#' -f 3)
  WHEN=$(echo $commit | cut -d'#' -f 4)
  printf "%4d %-7s %-20s %-20s %s\n" "${N}" "${H}" "${WHO}" "${WHEN}" "${S}" 
done < <(git --no-pager log -n 10 "$@" --pretty="%h#%s#%cn#%cr")