#!/bin/bash

if [ ! -f .gitignore ]; then
  cat > .gitignore << EOF
.env*
EOF
fi

if [ ! -f .dockerignore ]; then
  cat > .dockerignore << EOF
.env*
EOF
fi

if [ ! -f .envrc ]; then
  cat > .envrc << EOF
export PYTHONPATH=.:$(pipenv --py)
export PIPENV_SKIP_LOCK=true
export PIPENV_VERBOSITY=-1
EOF
fi

touch .env